#+title: Emacs From Scratch Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes :results none
#+STARTUP: overview

* Fonts and BG

#+begin_src emacs-lisp

  (defvar efs/default-font-size 140)
  (defvar efs/default-variable-font-size 140)

  ;; Make frame transparency overridable
  (defvar efs/frame-transparency '(90 . 90))

#+end_src

* Startup Performance

#+begin_src emacs-lisp

  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 50 1000 1000))

  (defun efs/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                      (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'efs/display-startup-time)

#+end_src

* Package System Setup

Emacs has a built in package manager but it doesn't make it easy to automatically install packages on a new system the first time you pull down your configuration. [[https://github.com/jwiegley/use-package][use-package]] is a really helpful package used in this configuration to make it a lot easier to automate the installation and configuration of everything else we use.

#+begin_src emacs-lisp

  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
  (setq use-package-always-defer nil)

#+end_src

** Automatic Package Updates

The auto-package-update package helps us keep our Emacs packages up to date!  It will prompt you after a certain number of days either at startup or at a specific time of day to remind you to update your packages.

You can also use =M-x auto-package-update-now= to update right now!

#+begin_src emacs-lisp

  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))

#+end_src

* Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp

  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  					;(setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering)

  ;; no-littering doesn't set this by default so we must place
  ;; auto save files in the same path as it uses for sessions
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

#+end_src

* Basic UI Configuration

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  (column-number-mode)
  (global-display-line-numbers-mode t)
  (setq display-line-numbers-type 'relative)

  ;; Set frame transparency
  (set-frame-parameter (selected-frame) 'alpha efs/frame-transparency)
  (add-to-list 'default-frame-alist `(alpha . ,efs/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable GUI prompts
  (setq use-dialog-box nil)
  (setq use-file-dialog-box nil)
  (setq use-short-answers t)  ;y/n

  ;; Open windows on the right by default
  (setq split-height-threshold nil)
  (setq split-width-threshold 0)

  ;; Save place mode
  (save-place-mode t)

  ;; Desktop Save mode on
  (desktop-save-mode 1)

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  treemacs-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Font Configuration

#+begin_src emacs-lisp

  (defun efs/set-font-faces ()
    (message "Setting Faces")
    (set-face-attribute 'default nil :font "Iosevka Curly" :height efs/default-font-size)

    ;; Set the fixed pitch face
    (set-face-attribute 'fixed-pitch nil :font "Iosevka Curly" :height efs/default-font-size)

    ;; Set the variable pitch face
    (set-face-attribute 'variable-pitch nil :font "Iosevka Aile" :height efs/default-variable-font-size :weight 'regular))

  (if (daemonp)
      (add-hook 'after-make-frame-functions
  	      (lambda (frame)
  		;; (setq doom-modeline-icon t)
  		(with-selected-frame frame
  		  (efs/set-font-faces))))
    (efs/set-font-faces))

#+end_src

* Keybinding Configuration

This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.  [[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.  [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package general
    :after evil
    :config

    (general-define-key
      :states '(normal insert visual emacs)
      :prefix-map 'efs/leader-map
      :prefix "SPC"
      :non-normal-prefix "M-SPC")
    
    (general-create-definer efs/leader-keys
      :keymaps 'efs/leader-map)

    (general-create-definer efs/local-leader-keys
      :states '(normal visual motion)
      :prefix ","
      :non-normal-prefix "M-,")
    
    (efs/leader-keys
      ;; M-x
      "SPC" '(execute-extended-command :which-key "M-x")
      "/" '(consult-ripgrep :which-key "Search Project")
      "!" '(shell-command :which-key "shell")
      "u" '(universal-argument :wk "Universal Argument")
      
      ;; HELP
      "h" '(:ignore t :which-key "help")
      "hf" '(describe-function :which-key "describe function")
      "hm" '(describe-mode :which-key "describe mode")
      "hb" '(describe-bindings :which-key "describe bindings")
      "hv" '(describe-variable :which-key "describe variable")
      "hk" '(describe-key :which-key "describe key")
      "hx" '(describe-command :which-key "describe command")
      "ho" '(describe-symbol :which-key "describe symbol")
      "hs" '(describe-syntax :which-key "describe syntax")
      "hrr" '((lambda () (interactive) (load-file user-init-file)) :which-key "reload config")

      ;; BUFFERS
      "b" '(:ignore t :which-key "bufs")
      "bb" '(consult-buffer  :which-key "switch")
      "bk" '(kill-current-buffer :which-key "kill")
      "be" '(erase-buffer :which-key "erase")
      "bs" '(scratch-buffer :which-key "scratch")

      ;; WINDOWS
      "w" '(:ignore t :wk "windows")
      "wh" '(evil-window-left :wk "left")
      "wj" '(evil-window-down :wk "down")
      "wk" '(evil-window-up :wk "up")
      "wl" '(evil-window-right :wk "right")
      "ww" '(evil-window-next :wk "next")

      "wH" '(evil-window-move-far-left :wk "move left")
      "wJ" '(evil-window-move-very-bottom :wk "move down")
      "wK" '(evil-window-move-very-top :wk "move up")
      "wL" '(evil-window-move-far-right :wk "move right")

      "w+" '((lambda () (interactive)
               (evil-window-increase-height 5))
             :which-key "increase height")

      "w-" '((lambda () (interactive)
               (evil-window-decrease-height 5))
  	   :which-key "decrease height")

      "w>" '((lambda () (interactive)
               (evil-window-increase-width 5))
  	   :which-key "increase width")

      "w<" '((lambda () (interactive)
               (evil-window-decrease-width 5))
  	   :which-key "decrease width")

      "ws" '(evil-window-split :wk "split")
      "wv" '(evil-window-vsplit :wk "vsplit")

      "wq" '(evil-window-delete :wk "quit")

      ;; FILES
      "." '(find-file :which-key "find file")
      "f" '(:ignore t :which-key "files")
      "fp" '(:ignore t :wk "perso agenda")
      ;; "fpp" '(lambda () (interactive) (efs/open-org-file efs/org-perso-file))
      ;; "fpi" '(lambda () (interactive) (efs/open-org-file efs/org-inbox-file))
      ;; "fpl" '(lambda () (interactive) (efs/open-org-file efs/org-logbook-archive-file) "logbook.org")
      "fde" '(lambda () (interactive) (find-file (expand-file-name "~/.config/emacs/init.org")))))

  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump t)
    (setq evil-undo-system 'undo-redo)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-c") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)
    (define-key evil-insert-state-map (kbd "C-v") #'yank)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))

#+end_src

** Evil GC commenting
Emulate gc binding nvim behaviour

#+begin_src emacs-lisp
  (use-package evil-commentary
    :after evil
    :config
    (evil-commentary-mode))
#+end_src

* UI Configuration

** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp

  (use-package command-log-mode
    :commands command-log-mode)

#+end_src

** Colour Theme

Gruvbox FTW

#+begin_src emacs-lisp

  (use-package doom-themes
    :init (load-theme 'doom-gruvbox t))

#+end_src

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

    (use-package all-the-icons
      :after doom-modeline)

    (use-package doom-modeline
      :hook (after-init . doom-modeline-mode)
      :custom ((doom-modeline-height 15)))

#+end_src

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src

** Vertico and Consult with Marginalia and Orderless

Replace =Ivy= with a =minad= stack

#+begin_src emacs-lisp
  ;; Completion UI
  (use-package vertico
    :bind (:map vertico-map
  	      ("C-j" . vertico-next)
  	      ("C-k" . vertico-previous)
  	      ("C-f" . vertico-exit)
  	      :map minibuffer-local-map
  	      ("M-h" . backward-kill-word))
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode))

  (use-package savehist
    :init
    (savehist-mode))

  ;; Rich annotations
  (use-package marginalia
    :after vertico
    :init
    (marginalia-mode))

  ;; Better matching
  (use-package orderless
    :after vertico
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides
     '((file (styles partial-completion)))))

  ;; Counsel replacement
  (use-package consult
    :bind (("C-s" . consult-line)
           ("C-M-j" . consult-buffer)
           :map minibuffer-local-map
           ("C-r" . consult-history)))

  ;; Optional but highly recommended
  (use-package embark
    :bind
    (("C-." . embark-act)
     ("C-;" . embark-dwim)
     ("C-h B" . embark-bindings)))

  (use-package embark-consult
    :after (embark consult))

#+end_src

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :bind
    ([remap describe-function] . helpful-callable)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key))

#+end_src

* Org Mode

[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

** Better Font Faces

The =efs/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp

  (defun efs/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Iosevka Aile" :weight 'light :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))

#+end_src

** Path Variables

Set up paths to org-files so that i can easily rename them later

#+begin_src emacs-lisp

  (defconst efs/org-directory
    (expand-file-name "~/Org/")
    "Root directory for Org files.")

  ;;;; Directories

  (defconst efs/org-archives-directory
    (expand-file-name "archives/" efs/org-directory))

  (defconst efs/org-projects-directory
    (expand-file-name "projects/" efs/org-directory))

  (defconst efs/org-logbooks-directory
    (expand-file-name "logbooks/" efs/org-archives-directory))

  (defconst efs/org-archive-projects-directory
    (expand-file-name "projects/" efs/org-archives-directory))

  ;;;; Files

  (defconst efs/org-inbox-file
    (expand-file-name "inbox.org" efs/org-directory))

  (defconst efs/org-perso-file
    (expand-file-name "perso.org" efs/org-directory))

  (defconst efs/org-habits-file
    (expand-file-name "habits.org" efs/org-directory))

  (defconst efs/org-logbook-archive-file
    (expand-file-name "logbook.org_archive"
                      efs/org-logbooks-directory))

  (defun efs/org-project-files ()
    "Return all Org files in the projects directory."
    (directory-files-recursively
     efs/org-projects-directory
     "\\.org$"))

  (defun efs/org-archive-files ()
    "Return all Org files in the archives directory."
    (directory-files-recursively
     efs/org-archives-directory
     "\\.org$"))

#+end_src

Open files if exist function

#+begin_src emacs-lisp

  (defun efs/open-org-file (file)
  "Open FILE if it exists, otherwise create it and open it."
  (interactive "fOrg file: ")
  (unless (file-exists-p file)
    (make-directory (file-name-directory file) t)
    (write-region "" nil file))
  (find-file file))

#+end_src

** Basic Config

This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.  There's a lot to unpack in here so I'd recommend watching the videos for [[https://youtu.be/VcgjTEa0kU4][Part 5]] and [[https://youtu.be/PNE-mgkZ6HM][Part 6]] for a full explanation.

#+begin_src emacs-lisp

  (defun org-journal-find-location ()
    ;; Open today's journal, but specify a non-nil prefix argument in order to
    ;; inhibit inserting the heading; org-capture will insert the heading.
    (org-journal-new-entry t)
    (unless (eq org-journal-file-type 'daily)
      (org-narrow-to-subtree))
    (goto-char (point-max)))

  (defun efs/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (use-package org
    :pin org
    :hook (org-mode . efs/org-mode-setup)
    :general
    (efs/leader-keys
      "a"  'org-agenda :wk "agenda"
      "c" 'org-capture :wk "capture")
    
    :general-config
    (efs/local-leader-keys
      :keymaps 'org-mode-map
      ;; Checkboxes
      "SPC" '(org-toggle-checkbox :wk "toggle checkbox")
      ;; Edit source
      "'" '(org-edit-src-code :wk "edit source")
      ;; TODOs
      "t"  '(org-todo :wk "todo")
      ;; Dates
      "d"  '(org-deadline :wk "deadline")
      "s"  '(org-schedule :wk "schedule")
      "T"  '(org-time-stamp :wk "timestamp")
      ;; Headings
      "h"  '(:ignore t :wk "heading")
      "hh" '(org-insert-heading :wk "insert")
      "ht" '(org-insert-todo-heading :wk "todo heading")
      "hu" '(org-up-element :wk "up")
      "hn" '(org-next-visible-heading :wk "next")
      "hp" '(org-previous-visible-heading :wk "prev")
      ;; Subtree
      "x"  '(:ignore t :wk "subtree")
      "xa" '(org-archive-subtree :wk "archive")
      "xr" '(org-refile :wk "refile")
      "xk" '(org-cut-subtree :wk "cut")
      "xy" '(org-copy-subtree :wk "copy")
      ;; Priority
      "p"  '(:ignore t :wk "priority")
      "pp" '(org-priority :wk "set")
      ;; Links
      "l"  '(:ignore t :wk "links")
      "ll" '(org-cliplink :wk "cliplink")
      "li" '(org-insert-link :wk "insert")
      "ls" '(org-store-link :wk "store")
      "lm" '(org-download-clipboard :wk "insert media")
      "lo" '(org-open-at-point :wk "open")
      "ln" '(org-next-link :wk "next")
      "lp" '(org-previous-link :wk "prev")
      ;; Tables
      "b"  '(:ignore t :wk "table")
      "ba" '(org-table-align :wk "align")
      "br" '(org-table-recalculate :wk "recalc")
      ;; Clocking
      "c"  '(:ignore t :wk "clock")
      "ci" '(org-clock-in :wk "in")
      "co" '(org-clock-out :wk "out")
      "cr" '(org-clock-report :wk "report")
      ;; Navigation
      "g"  '(:ignore t :wk "goto")
      "gc" '(org-goto :wk "goto")
      "gi" '(org-id-get-create :wk "create id")
      ;; Visibility
      "v"  '(:ignore t :wk "visibility")
      "vc" '(org-cycle :wk "cycle")
      "va" '(org-cycle-global :wk "global cycle")
      ;; Export
      "e"  '(:ignore t :wk "export")
      "eh" '(org-html-export-to-html :wk "html")
      "ep" '(org-latex-export-to-pdf :wk "pdf")
      ;; Babel
      "r"  '(:ignore t :wk "run")
      "rb" '(org-babel-execute-src-block :wk "block")
      "ra" '(org-babel-execute-buffer :wk "buffer"))

    (general-define-key
     :states 'normal
     :keymaps 'org-agenda-mode-map
     "e" #'org-agenda-set-effort
     "c" #'org-agenda-capture
     "M-j" #'org-agenda-priority-down
     "M-k" #'org-agenda-priority-up
     "M-l" #'org-agenda-todo-nextset
     "M-h" #'org-agenda-todo-previousset)

    (general-define-key
     :definer 'minor-mode
     :states 'normal
     :keymaps 'org-capture-mode
     "M-f" 'org-capture-finalize
     "M-r" 'org-capture-refile
     "M-k" 'org-capture-kill)

    (general-define-key
     :definer 'minor-mode
     :states 'normal
     :keymaps 'org-src-mode
     "M-f" 'org-edit-src-exit
     "M-k" 'org-edit-src-abort)

    :config
    (setq org-ellipsis " ")

    (setq org-agenda-start-with-log-mode t)
    (setq org-log-done 'time)
    (setq org-log-into-drawer t)

    (setq org-clock-in-switch-to-state "CURR")

    (setq org-special-ctrl-a/e t)
    (setq org-M-RET-may-split-line nil)

    (setq org-effort-property "EFFORT")

    (setq org-agenda-files
          (append
           (list efs/org-inbox-file
                 efs/org-perso-file
                 efs/org-habits-file)
           (efs/org-archive-files)
           (efs/org-project-files)))
    
    (setq org-agenda-window-setup 'only-window)

    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60)

    (setq org-todo-keywords
          '((sequence "TODO(t)" "CURR(c!)" "HOLD(h@)"
                      "|"
                      "DONE(d)" "ABRT(a@)")
            (sequence "MEET(m)"
                      "|"
                      "DONE(d)" "ABRT(a@)")))

    ;; Save Org buffers after refiling
    (advice-add 'org-refile :after #'org-save-all-org-buffers)

    (setq org-tag-alist
          '(("@URGENT" . ?u)
            ("@REFILE" . ?r)
            ("@CURR" . ?c)))

    (setq efs/org-filetags
          '("@PERSO" "@PROJECT" "@WORK"))

    (defun efs/agenda-skip-tags (&rest args)
      "Skip tags passed as ARGS in the agenda view."
      (let (beg end)
        (org-back-to-heading t)
        (setq beg (point)
              end (progn (outline-next-heading)
                         (1- (point))))
        (goto-char beg)
        (setq alltags (prin1-to-string (org-get-tags)))
        (goto-char beg)
        (if (-some (lambda (x)
                     (string-match x alltags))
                   args)
            end)))

    (defun efs/agenda-skip-property (property value)
      "Skip an agenda entry if PROPERTY equals VALUE."
      (let ((subtree-end (save-excursion
                           (org-end-of-subtree t))))
        (if (string=
             (org-entry-get nil property)
             value)
            subtree-end
          nil)))

    (setopt org-agenda-sorting-strategy
            '((agenda time-up deadline-up scheduled-up todo-state-up priority-down)
              (todo todo-state-up priority-down deadline-up)
              (tags todo-state-up priority-down deadline-up)
              (search todo-state-up priority-down deadline-up)))

    (setq org-agenda-prefix-format
          "%-10:c %-12t %-6e %s")

    (setq org-agenda-hide-tags-regexp
          (mapconcat #'identity
                     efs/org-filetags
                     "\\|"))

    (setq efs/org-perso-agenda-views
          '(("p" "Perso agenda"
             (
              (agenda ""
                      ((org-agenda-show-all-dates nil)
                       (org-agenda-use-time-grid nil)
                       (org-agenda-span 14)
                       (org-agenda-start-on-weekday nil)
                       (org-deadline-warning-days 14)
                       (org-agenda-show-log t)
                       (org-agenda-skip-function
                        '(efs/agenda-skip-tags "@WORK"))))

              (tags "@PERSO+@REFILE|@PERSO+@URGENT"
                    ((org-agenda-overriding-header
                      "Inbox || Urgent:")))

              (tags-todo "@PERSO+@CURR|@PERSO+TODO={CURR}|@PERSO+TODO={HOLD}"
                         ((org-agenda-overriding-header
                           "In Progress:")
                          (org-agenda-skip-function
                           '(or
                             (efs/agenda-skip-property
                              "STYLE"
                              "habit")
                             (efs/agenda-skip-tags
                              "monthlygoals")))))

              (tags "@PERSO+monthlygoals-TODO={DONE}"
                    ((org-agenda-overriding-header
                      "Monthly Goals:")))

              (tags-todo "@PERSO+TODO={TODO}-@REFILE"
                         ((org-agenda-overriding-header
                           "Next:")
                          (org-agenda-skip-function
                           '(or
                             (org-agenda-skip-entry-if
                              'scheduled)
                             (org-agenda-skip-entry-if
                              'deadline)
                             (efs/agenda-skip-property
                              "STYLE"
                              "habit")
                             (efs/agenda-skip-tags
                              "monthlygoals")))))

              (todo "DONE|ABRT"
                    ((org-agenda-overriding-header
                      "Completed:")
                     (org-agenda-skip-function
                      '(efs/agenda-skip-tags
                        "@WORK"
                        "monthlygoals"))))))))

    (setq org-agenda-custom-commands
          (append org-agenda-custom-commands
                  efs/org-perso-agenda-views))

    (setq org-refile-targets
          `((,efs/org-inbox-file
             :maxlevel . 5)
            (,efs/org-perso-file
             :maxlevel . 5)
            (,(efs/org-project-files)
             :maxlevel . 5)))

    (setq org-capture-templates
          `(("p" "Perso Capture")

            ("pt" "Task"
             entry
             (file ,efs/org-inbox-file)
             "* TODO [#B] %^{task} %^g\n  :LOGBOOK:\n  - CREATED: %U\n  :END:\n%?\n")

            ("pn" "Note"
             entry
             (file ,efs/org-inbox-file)
             "* %^{item} %^g\n  :LOGBOOK:\n  - CREATED: %U\n  :END:\n%?\n")

            ("pm" "Meeting"
             entry
             (file ,efs/org-inbox-file)
             "* MEET [#A] %^{meeting} %^g\n  SCHEDULED: %^T\n  :LOGBOOK:\n  - CREATED: %U\n  :END:\n%?\n")

  	  ("pj" "Journal"
  	   plain
  	   (function org-journal-find-location)
  	   "** %(format-time-string org-journal-time-format)%^{Title}\n%i%?"
  	   :jump-to-captured t :immediate-finish t)))

    (efs/org-font-setup))

#+end_src

*** Centre Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to centre =org-mode= buffers for a more pleasing writing experience as it centres the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behaviour.

#+begin_src emacs-lisp

  (defun efs/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :defer t
    :hook (org-mode . efs/org-mode-visual-fill))

#+end_src

** Org-Journal

[[https://github.com/bastibe/org-journal][Org-Journal]] is the package for creating and managing your own digital diary within the comfort of Emacs.

#+begin_src emacs-lisp

  (use-package org-journal
    :commands (org-journal-new-entry)
    :general
    (efs/leader-keys
      "j" '(:ignore t :wk "journal")
      "jn" 'org-journal-new-entry)
    :general-config
    (general-define-key
      :keymaps 'org-journal-mode
      :states 'normal
      "M-n" 'org-journal-next-entry
      "M-p" 'org-journal-previous-entry)
    :init
    (setq org-journal-prefix-key nil)
    :config
    (setq org-journal-dir (expand-file-name "diary/" efs/org-directory))
    (setq org-journal-file-format "%Y-%m-%d.org"))
    
#+end_src

** Evil Org Bindings

#+begin_src emacs-lisp

  (use-package evil-org
    :after org
    :hook (org-mode . evil-org-mode)
    :config
    (evil-org-set-key-theme
     '(navigation
       insert
       textobjects
       additional
       shift
       todo)))

#+end_src

** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (python . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))

#+end_src

** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("py" . "src python")))

#+end_src

** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =efs/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (expand-file-name user-emacs-directory))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))

#+end_src

** Org-Modern

Better-looking org files

#+begin_src emacs-lisp

  (use-package org-modern
    :defer t
    :config
    (setopt org-modern-star 'replace)
    (setopt org-modern-replace-stars "◉○●")
    :hook
    (org-mode . org-modern-mode)
    (org-agenda-finalize . org-modern-agenda))

#+end_src

** Org-Appear

#+begin_src emacs-lisp

  (use-package org-appear
    :defer t
    :commands (org-appear-mode)
    :hook (org-mode . org-appear-mode)
    :config
    (setq org-hide-emphasis-markers t)
    (setq org-appear-autoemphasis t
  	org-appear-autolinks    t
  	org-appear-autosubmarkers t))

#+end_src

** Org-Cliplink

[[https://github.com/rexim/org-cliplink][Org-cliplink]] is a package that inserts pretty online links in org.

#+begin_src emacs-lisp

  (use-package org-cliplink
    :defer t
    :commands (org-cliplink))

#+end_src

** Spellchecker

[[https:https://github.com/minad/jinx][Jinx]] seems to be the way to go for spellchecking in Emacs nowadays.

Dependencies:
1. =enchant= (installed via pacman)
2. =hunspell= (or any dictionary)

#+begin_src emacs-lisp

  (use-package jinx
    :defer t
    :hook (text-mode . jinx-mode)
    :bind ([remap ispell-word] . jinx-correct)
    :custom
    (jinx-languages "en_GB"))

#+end_src

** Org-Download

[[https://github.com/abo-abo/org-download][Org-Download]] Is a package that allows to easily download and insert images into org files

#+begin_src emacs-lisp

  (use-package org-download
    :defer t
    :commands (org-download-clipboard)
    :config
    (setq org-download-method 'directory
          org-download-image-dir (concat (file-name-sans-extension
                                        (file-name-nondirectory (buffer-file-name)))
                                                 "-img")
          org-download-heading-lvl nil
          org-image-actual-width 600)
    (add-hook 'dired-mode-hook #'org-download-enable))

#+end_src

** Org-Present
Org-Present for pretty presentations just in case

#+begin_src emacs-lisp
    
    (use-package org-present
      :commands (org-present))

#+end_src

* Org Roam

[[https://www.orgroam.com/][Org-roam]] Is a package that helps with quickly capturing and organising notes in org-files leveraging Zettelkasten system.

#+begin_src emacs-lisp

  (use-package org-roam
    :commands (org-roam-node-find org-roam-node-insert)
    :general
    (efs/leader-keys
      "n" '(:ignore t :wk "Org-Roam")
      "nf" '(org-roam-node-find :wk "find node")
      "ni" '(org-roam-node-insert :wk "insert node")
      "nc" '(org-roam-capture :wk "capture node")
      "nd" '(:ignore t :wk "dailies")
      "ndY" '(org-roam-dailies-capture-yesterday :wk "Capture yesterday")
      "ndy" '(org-roam-dailies-find-today :wk "Go to today")
      "ndT" '(org-roam-dailies-capture-today :wk "Capture today")
      "ndt" '(org-roam-dailies-find-today :wk "Go to today"))
    :general-config
    (efs/leader-keys
      "nb" '(org-roam-buffer-toggle :wk "toggle buffer")
      "nR" '(org-roam-node-random :wk "random node")
      "nr" '(org-roam-refile :wk "refile")
      )
    :custom
    (org-roam-directory (expand-file-name "roam/" efs/org-directory)))

#+end_src

* Development

** LSP

#+begin_src emacs-lisp

  (use-package eglot
    :hook (prog-mode . eglot-ensure))

#+end_src

** Corfu and Cape
Modern completions stack

#+begin_src emacs-lisp
  (use-package corfu
    :custom
    (corfu-auto t)
    (corfu-auto-prefix 3)
    (corfu-auto-delay 0.2)
    (corfu-cycle t)
    (corfu-preview-current t)
    (corfu-preselect 'prompt)

    :bind
    (:map corfu-map
          ("C-n" . corfu-next)
          ("C-p" . corfu-previous)
          ("RET" . corfu-insert))

    :init
    (global-corfu-mode))

  (use-package emacs
    :custom
    (tab-always-indent 'complete))

  (use-package cape
    :init
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file))
#+end_src

*** Corfu Icons

#+begin_src emacs-lisp
  (use-package kind-icon
    :after corfu
    :custom
    (kind-icon-default-face 'corfu-default)
    :config
    (add-to-list 'corfu-margin-formatters
                 #'kind-icon-margin-formatter))
#+end_src

** Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'auto))
    :general
    (efs/leader-keys
      "p" '(:keymap projectile-command-map :wk "projectile"))
    :init

    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/Projects/")
      (setq projectile-project-search-path '("~/Projects/")))
    (when (file-directory-p "~/Org/")
      (setq projectile-project-search-path '("~/Org/")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package consult-projectile
    :after projectile)
#+end_src

** Magit

[[https://magit.vc/][Magit]] is the best Git interface I've ever used.  Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp

  (use-package magit
    :general
    (efs/leader-keys
      "g" '(:ignore t :which-key "git")
      "gs" '(magit-status :which-key "status")
      "gi" '(magit-init :which-key "init"))
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge
    :after magit)

#+end_src

** Commenting

Emacs' built in commenting functionality =comment-dwim= (usually bound to =M-;=) doesn't always comment things in the way you might expect so we use [[https://github.com/redguardtoo/evil-nerd-commenter][evil-nerd-commenter]] to provide a more familiar behaviour.  I've bound it to =M-/= since other editors sometimes use this binding but you could also replace Emacs' =M-;= binding with this command.

#+begin_src emacs-lisp

  (use-package evil-nerd-commenter
    :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colourizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

** Javelin

=Javelin.el= is a package providing similar functionality to =Harpoon= in neovim. Used for quickly jumping between recorded locations.

#+begin_src emacs-lisp

  (use-package javelin
    :defer t
    :config
    (global-javelin-minor-mode 1))

#+end_src

* Terminals
** Vterm

#+begin_src emacs-lisp
  
  (use-package vterm
    :general
    (efs/leader-keys
      "tt" 'vterm-other-window
      "to" 'vterm))

#+end_src

* File Management

** Dired

Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:

*** Key Bindings

**** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp

  (use-package dired
    :ensure nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-up-directory
      "l" 'dired-find-file))

  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))

  (use-package dired-open
    :commands (dired dired-jump)
    :config
    ;; Doesn't work as expected!
    ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
                                  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))

#+end_src

* Runtime Performance

Dial the GC threshold back down so that garbage collection happens more frequently but in less time.

#+begin_src emacs-lisp

  ;; Make gc pauses faster by decreasing the threshold.
  (setq gc-cons-threshold (* 2 1000 1000))

#+end_src
